In [5]:
# importing numpy to use array
import numpy as np

In [2]:
# defining the playing cards deck with 4 aces and 48 non-aces
deck0 = np.zeros(48)
deck1 = np.ones(4)
deck = np.hstack((deck0, deck1))

In [3]:
deck0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
deck1

array([1., 1., 1., 1.])

In [5]:
deck

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1.])

In [6]:
# defining a function that finds the location of the first ace appearance in a deck
def find_first_ace(A):
    p=1
    for i in range(A.size):
        if A[i]==1:
            return p
        else:
            p = p+1

In [7]:
# shuffling the aces in the deck
np.random.shuffle(deck)

# printing the location of the first ace
print(find_first_ace(deck))

deck

1


array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1.])

In [8]:
# suffling the deck "trials" times, find the location of the first ace each time and save it in a list called FAL
trials = 100000
FAL = []
for i in range(trials):
    np.random.shuffle(deck)
    fa = find_first_ace(deck)
    FAL.append(fa)

# find the avearge or mean of the list FAL
FAL_avg = np.mean(FAL)

# printing the value of the first ace average and showing the FAL
print(f"First ace average place is: {FAL_avg}")

#FAL


First ace average place is: 10.58641


In [9]:
# defining a function that finds the location of the second ace appearance in a deck
def find_second_ace(A):
    p = find_first_ace(A)
    n=1
    for i in range(p, A.size):
        if A[i]==1:
            return p+n
        else:
            n = n+1

In [10]:
# shuffling the aces in the deck
np.random.shuffle(deck)

# printing the location of the first and second ace
print(f"First ace: {find_first_ace(deck)}")
print(f"Second ace: {find_second_ace(deck)}")

deck

First ace: 4
Second ace: 19


array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [11]:
# suffling the deck "trials" times, find the location of the second ace each time and save it in a list called SAL
trials = 100000
SAL = []
for i in range(trials):
    np.random.shuffle(deck)
    sa = find_second_ace(deck)
    SAL.append(sa)

# find the avearge or mean of the list FAL
SAL_avg = np.mean(SAL)

# printing the value of the first ace average and showing the FAL
print(f"The second ace average place is: {SAL_avg}")

#SAL

The second ace average place is: 21.22634


In [61]:
# For illustration purposes
import random
dec0 = np.zeros(48).astype(int).tolist()
decA = ['A','A','A','A']
dec = dec0 +decA


print(dec,"\n \n")

random.shuffle(dec)
print("Shuffle 1: ",dec,"\n")
random.shuffle(dec)
print("Shuffle 2: ",dec,"\n")
random.shuffle(dec)
print("Shuffle 3: ",dec)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'A', 'A', 'A', 'A'] 
 

Shuffle 1:  [0, 0, 0, 0, 0, 0, 0, 0, 'A', 0, 0, 0, 0, 0, 0, 'A', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'A', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'A', 0] 

Shuffle 2:  [0, 0, 0, 0, 0, 0, 0, 'A', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'A', 0, 0, 0, 0, 0, 'A', 0, 0, 0, 0, 'A', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 

Shuffle 3:  [0, 'A', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'A', 0, 0, 0, 'A', 0, 0, 0, 0, 0, 0, 'A', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
