In [16]:
# importing numpy to use array
import numpy as np

In [17]:
# defining the playing cards deck with 4 aces and 48 non-aces
deck0 = np.zeros(48)
deck1 = np.ones(4)
deck = np.hstack((deck0, deck1))

In [18]:
deck0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
deck1

array([1., 1., 1., 1.])

In [20]:
deck

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1.])

In [21]:
# defining a function that finds the location of the first ace appearance in a deck
def find_first_ace(A):
    p=1
    for i in range(A.size):
        if A[i]==1:
            return p
        else:
            p = p+1

In [22]:
# shuffling the aces in the deck
np.random.shuffle(deck)

# printing the location of the first ace
print(find_first_ace(deck))

deck

5


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [12]:
# suffling the deck "trials" times, find the location of the first ace each time and save it in a list called FAL
trials = 100000
FAL = []
for i in range(trials):
    np.random.shuffle(deck)
    fa = find_first_ace(deck)
    FAL.append(fa)

# find the avearge or mean of the list FAL
FAL_avg = np.mean(FAL)

# printing the value of the first ace average and showing the FAL
print(f"First ace average place is: {FAL_avg}")
FAL


First ace average place is: 10.61437


[20,
 10,
 12,
 8,
 3,
 13,
 9,
 19,
 12,
 16,
 9,
 11,
 2,
 5,
 3,
 8,
 1,
 3,
 2,
 7,
 2,
 2,
 7,
 19,
 4,
 4,
 9,
 10,
 10,
 16,
 8,
 2,
 9,
 19,
 8,
 10,
 12,
 13,
 4,
 13,
 9,
 3,
 7,
 4,
 6,
 8,
 9,
 15,
 5,
 6,
 3,
 15,
 4,
 6,
 24,
 6,
 6,
 19,
 2,
 5,
 5,
 1,
 1,
 13,
 10,
 1,
 6,
 1,
 9,
 1,
 16,
 1,
 4,
 3,
 3,
 20,
 1,
 2,
 6,
 10,
 23,
 6,
 6,
 1,
 1,
 12,
 18,
 4,
 12,
 1,
 9,
 3,
 20,
 5,
 16,
 29,
 15,
 26,
 15,
 14,
 19,
 25,
 12,
 6,
 3,
 14,
 20,
 14,
 13,
 22,
 5,
 12,
 6,
 13,
 18,
 1,
 16,
 13,
 2,
 4,
 10,
 6,
 1,
 22,
 24,
 15,
 7,
 29,
 24,
 5,
 6,
 17,
 3,
 10,
 9,
 10,
 7,
 9,
 6,
 10,
 11,
 11,
 2,
 3,
 9,
 2,
 4,
 3,
 8,
 18,
 3,
 39,
 15,
 5,
 10,
 12,
 1,
 36,
 7,
 9,
 9,
 7,
 9,
 2,
 3,
 2,
 19,
 1,
 17,
 2,
 2,
 11,
 39,
 16,
 9,
 27,
 2,
 3,
 3,
 14,
 7,
 4,
 3,
 6,
 3,
 19,
 4,
 21,
 19,
 1,
 11,
 7,
 4,
 15,
 1,
 20,
 14,
 16,
 3,
 5,
 8,
 17,
 35,
 19,
 9,
 11,
 3,
 22,
 7,
 9,
 6,
 8,
 7,
 15,
 5,
 13,
 6,
 5,
 5,
 16,
 7,
 3,
 12,
 19,
 8,
 10,
 2

In [31]:
# defining a function that finds the location of the second ace appearance in a deck
def find_second_ace(A):
    p = find_first_ace(A)
    n=1
    for i in range(p, A.size):
        if A[i]==1:
            return p+n
        else:
            n = n+1

In [43]:
# shuffling the aces in the deck
np.random.shuffle(deck)

# printing the location of the first and second ace
print(find_first_ace(deck))
print(find_second_ace(deck))

deck

3
21


array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0.])

In [52]:
# suffling the deck "trials" times, find the location of the second ace each time and save it in a list called SAL
trials = 100000
SAL = []
for i in range(trials):
    np.random.shuffle(deck)
    sa = find_second_ace(deck)
    SAL.append(sa)

# find the avearge or mean of the list FAL
SAL_avg = np.mean(SAL)

# printing the value of the first ace average and showing the FAL
print(f"The second ace average place is: {SAL_avg}")
SAL

The second ace average place is: 21.22917


[6,
 34,
 25,
 12,
 40,
 22,
 31,
 13,
 40,
 12,
 29,
 5,
 25,
 16,
 36,
 20,
 21,
 3,
 3,
 9,
 29,
 6,
 8,
 46,
 31,
 42,
 33,
 19,
 23,
 25,
 3,
 22,
 12,
 7,
 30,
 13,
 14,
 42,
 33,
 19,
 8,
 17,
 41,
 43,
 38,
 11,
 38,
 9,
 22,
 16,
 14,
 5,
 26,
 25,
 22,
 8,
 34,
 28,
 41,
 13,
 36,
 11,
 25,
 6,
 7,
 11,
 20,
 27,
 36,
 31,
 25,
 29,
 9,
 20,
 39,
 27,
 43,
 23,
 34,
 10,
 20,
 37,
 30,
 17,
 25,
 24,
 13,
 11,
 6,
 9,
 18,
 14,
 10,
 32,
 31,
 15,
 17,
 31,
 5,
 8,
 41,
 6,
 11,
 35,
 28,
 12,
 28,
 31,
 23,
 25,
 8,
 31,
 9,
 17,
 27,
 5,
 29,
 25,
 23,
 20,
 30,
 15,
 6,
 16,
 33,
 10,
 27,
 7,
 20,
 30,
 27,
 26,
 14,
 20,
 23,
 28,
 25,
 37,
 15,
 24,
 9,
 38,
 36,
 33,
 29,
 34,
 23,
 42,
 12,
 27,
 14,
 35,
 17,
 20,
 41,
 11,
 23,
 7,
 11,
 11,
 16,
 28,
 45,
 37,
 14,
 3,
 33,
 13,
 14,
 10,
 30,
 25,
 14,
 11,
 30,
 13,
 34,
 15,
 7,
 4,
 22,
 15,
 18,
 24,
 10,
 12,
 16,
 28,
 36,
 33,
 45,
 20,
 30,
 6,
 19,
 37,
 7,
 25,
 19,
 16,
 18,
 14,
 19,
 33,
 14,
 12,
 6,